services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: cours_data_api
    ports:
      - "80:5000"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - postgres
    networks:
      - app_network
    restart: unless-stopped
    command: ["python3", "src/api.py"]

  postgres:
    image: postgres:15
    container_name: cours_data_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cours_data
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: cours_data_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "54321:80"
    depends_on:
      - postgres
    networks:
      - app_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app_network:
